name: ros2-pipeline-test

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - run: |
          # Set up sources
          sudo apt update && sudo apt install -y curl gnupg lsb-release
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          # Install ROS 2 Jazzy packages
          sudo apt update
          sudo apt install -y ros-jazzy-desktop
          # Source ROS 2 environment
          sudo apt install python3-colcon-common-extensions
      - run: |
          echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
          source ~/.bashrc
          source /opt/ros/jazzy/setup.bash
          mkdir -p ros2_ws/src/ros2_ci_cd
          ls /opt/ros
          ls ros2_ws
          cd ros2_ws
          colcon build
          source install/setup.bash
      - uses: actions/checkout@v3
        with:
          path: ros2_ws/src/ros2_ci_cd
      - run: |
          source /opt/ros/jazzy/setup.bash
          sudo apt install python3-rosdep
          sudo rosdep init
          rosdep update --include-eol-distros
          cd ros2_ws
          rosdep install --from-paths src -y --ignore-src
          colcon build 
